# Common configs#
# components/features specific test data configs should be created and
# the common configs should be kept to minimal with framework level or product level configuration

# Try to create test data on the fly with a fixture and log/cache that.
# for poc we are adding test data config to the common config which should be avoided


target_url: "https://petstore.swagger.io/v2"
test_1:
  - id: 0
    username: "ranjan"
    firstName: "ranjan"
    lastName: "naik"
    email: "test0@abc.com"
    password: "test@123"
    phone: "123-456789"
    userStatus: 0



